################################# Default configuration ###################
baseURL = "https://www.oramainteractive.com/"
title = "Orama Interactive"
theme = "meghna-hugo"
# post pagination
paginate = "6"
# post excerpt
summaryLength = "15"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = []

############################# Plugins ##########################
# css plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "plugins/fontawesome-free-6.6.0-web/all.min.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "https://fonts.googleapis.com/css?family=Anaheim|Quattrocento+Sans:400,700&display=swap"

# js plugins
[[params.plugins.js]]
link = "plugins/jquery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/lazy-load/lozad.min.js"
[[params.plugins.js]]
link = "plugins/google-map/map.js"

################### English Navigation ########################
[[Languages.en.menu.main]]
name = "About"
url = "#about"
weight = 1

[[Languages.en.menu.main]]
name = "Projects"
url = "#portfolio"
weight = 2

[[Languages.en.menu.main]]
name = "Team"
url = "#team"
weight = 3

[[Languages.en.menu.main]]
name = "Blog"
url = "#blog"
weight = 4

[[Languages.en.menu.main]]
name = "Contact"
url = "#contact"
weight = 5


################### Greek Navigation ########################
[[Languages.gr.menu.main]]
name = "Σχετικά"
url = "#about"
weight = 1

[[Languages.gr.menu.main]]
name = "Έργα"
url = "#portfolio"
weight = 2

[[Languages.gr.menu.main]]
name = "Ομάδα"
url = "#team"
weight = 3

[[Languages.gr.menu.main]]
name = "Επικοινωνία"
url = "#contact"
weight = 4

############################# Default Parameters ##########################
[params]
logo = "images/orama_logo.svg"
# Meta data
description = "Website of Orama Interactive"
author = "Orama Interactive"
# Google Analytics
google_analytics_id = "" # Your ID
# post share
post_share = true

# preloader
[params.preloader]
enable = false
preloader = "images/orama_logo.svg"

# cookies
[params.cookies]
enable = false
expire_days = 2


############################# Social icons ##########################
# Font Awesome icon pack: https://fontawesome.com/icons
[[params.social]]
icon = "fa-regular fa-envelope"
link = "mailto:oramagamestudios@gmail.com"

[[params.social]]
icon = "fa-brands fa-steam"
link = "https://store.steampowered.com/developer/Orama Interactive"

[[params.social]]
icon = "fa-brands fa-itch-io"
link = "https://orama-interactive.itch.io/"

[[params.social]]
icon = "fa-brands fa-patreon"
link = "https://www.patreon.com/OramaInteractive"

[[params.social]]
icon = "fa-brands fa-mastodon"
link = "https://mastodon.gamedev.place/@OramaInteractive"

[[params.social]]
icon = "fa-brands fa-github"
link = "https://github.com/Orama-Interactive"

[[params.social]]
icon = "fa-brands fa-bluesky"
link = "https://bsky.app/profile/oramainteractive.bsky.social"

[[params.social]]
icon = "fa-brands fa-youtube"
link = "https://www.youtube.com/c/OramaInteractive"

[[params.social]]
icon = "fa-brands fa-facebook"
link = "https://www.facebook.com/orama.interactive/"

[[params.social]]
icon = "fa-brands fa-instagram"
link = "https://www.instagram.com/orama_interactive/"


[Languages]
    [Languages.en]
        languageName = "English"
        languageCode = "en-us"
        contentDir = "content/english"
        [Languages.en.params]
            weight = 1
            home = "Home"
            copyright = "Copyright &copy; 2022 Theme by [Themefisher](https://themefisher.com) & Developed by Orama Interactive"

    [Languages.gr]
        languageName = "Greek"
        languageCode = "gr-el"
        contentDir = "content/greek"
        [Languages.gr.params]
            weight = 2
            home = "Αρχική"
            copyright = "Copyright &copy; 2022 Θέμα από [Themefisher](https://themefisher.com) & Ιστοσελίδα φτιαγμένη από την Orama Interactive"

[markup]
    [markup.goldmark.renderer]
      unsafe = true
