################################# Default configuration ###################
baseURL = ""
title = "Orama Interactive"
theme = "meghna-hugo"
# post pagination
paginate = "6"
# post excerpt
summaryLength = "15"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = []

############################# Plugins ##########################
# css plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "https://fonts.googleapis.com/css?family=Anaheim|Quattrocento+Sans:400,700&display=swap"

# js plugins
[[params.plugins.js]]
link = "plugins/jquery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/lazy-load/lozad.min.js"
[[params.plugins.js]]
link = "plugins/google-map/map.js"

################### English Navigation ########################
[[Languages.en.menu.main]]
name = "About"
url = "#about"
weight = 1

[[Languages.en.menu.main]]
name = "Projects"
url = "#portfolio"
weight = 2

[[Languages.en.menu.main]]
name = "Team"
url = "#team"
weight = 3

[[Languages.en.menu.main]]
name = "Blog"
url = "#blog"
weight = 4

[[Languages.en.menu.main]]
name = "Contact"
url = "#contact"
weight = 5


################### Greek Navigation ########################
[[Languages.gr.menu.main]]
name = "Σχετικά"
url = "#about"
weight = 1

[[Languages.gr.menu.main]]
name = "Έργα"
url = "#portfolio"
weight = 2

[[Languages.gr.menu.main]]
name = "Ομάδα"
url = "#team"
weight = 3

[[Languages.gr.menu.main]]
name = "Επικοινωνία"
url = "#contact"
weight = 4

############################# Default Parameters ##########################
[params]
logo = "images/orama_logo.svg"
# Meta data
description = "Website of Orama Interactive"
author = "Orama Interactive"
# Google Analytics
google_analytics_id = "" # Your ID
# post share
post_share = true

# preloader
[params.preloader]
enable = false
preloader = "images/orama_logo.svg"

# cookies
[params.cookies]
enable = false
expire_days = 2


############################# social icons ##########################
[[params.social]]
icon = "ti-email" # themify icon pack : https://themify.me/themify-icons
link = "mailto:oramagamestudios@gmail.com"

[[params.social]]
icon = "ti-facebook" # themify icon pack : https://themify.me/themify-icons
link = "https://www.facebook.com/orama.interactive/"

[[params.social]]
icon = "ti-twitter-alt" # themify icon pack : https://themify.me/themify-icons
link = "https://twitter.com/OramaInteractiv"

[[params.social]]
icon = "ti-youtube" # themify icon pack : https://themify.me/themify-icons
link = "https://www.youtube.com/c/OramaInteractive"

[[params.social]]
icon = "ti-github" # themify icon pack : https://themify.me/themify-icons
link = "https://github.com/Orama-Interactive"

[[params.social]]
icon = "ti-instagram" # themify icon pack : https://themify.me/themify-icons
link = "https://www.instagram.com/orama_interactive/"


################################ English Language ########################
[Languages.en]
languageName = "English"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
home = "Home"
copyright = "Copyright &copy; 2022 Theme by [Themefisher](https://themefisher.com) & Developed by Orama Interactive"

################################ France Language ########################
[Languages.gr]
languageName = "Greek"
languageCode = "gr-el"
contentDir = "content/greek"
weight = 2
home = "Αρχική"
copyright = "Copyright &copy; 2022 Θέμα από [Themefisher](https://themefisher.com) & Ιστοσελίδα φτιαγμένη από την Orama Interactive"
